theme: jekyll-theme-minimal
title: dendencat home page
description: Information about each repository link I have created and its documentation can be found here.
# domain: dendencat.github.io
# url: https://dendencat.github.io
# baseurl: "/dendencat.github.io/"